<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="WithLove.Workflows.Tests" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
        <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.8.3" />
        <PackageReference Include="Microsoft.OpenApi" Version="2.11.0" />
        <PackageReference Include="TemporalCommunity.Extensions.AI" Version="0.12.1" />
        <PackageReference Include="Temporalio.Extensions.DiagnosticSource" Version="1.17.0" />
        <PackageReference Include="Temporalio.Extensions.Hosting" Version="1.17.0" />
        <PackageReference Include="Temporalio.Extensions.OpenTelemetry" Version="1.17.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\WithLove.Data\WithLove.Data.csproj" />
      <ProjectReference Include="..\WithLove.ServiceDefaults\WithLove.ServiceDefaults.csproj" />
      <ProjectReference Include="..\WithLove.Workflows\WithLove.Workflows.csproj" />
    </ItemGroup>

</Project>
