// <auto-generated />

namespace WithLove.OpenInference;

/// <summary>OpenInference reserved attribute names from the pinned conventions manifest.</summary>
public static class OpenInferenceAttributes
{
    public const string DocumentContent = "document.content";
    public const string DocumentId = "document.id";
    public const string DocumentMetadata = "document.metadata";
    public const string DocumentScore = "document.score";
    public const string ExceptionEscaped = "exception.escaped";
    public const string InputMimeType = "input.mime_type";
    public const string InputValue = "input.value";
    public const string OpenInferenceProjectName = "openinference.project.name";
    public const string OpenInferenceSpanKind = "openinference.span.kind";
    public const string OutputMimeType = "output.mime_type";
    public const string OutputValue = "output.value";
    public const string RetrievalDocuments = "retrieval.documents";
    public const string SessionId = "session.id";
    public const string TagTags = "tag.tags";
    public const string ToolDescription = "tool.description";
    public const string ToolId = "tool.id";
    public const string ToolName = "tool.name";
    public const string UserId = "user.id";
}
