using System.Text;
using System.Text.Json;
using WithLove.OpenInference.Generator;

const string ManifestRelativePath = "src/WithLove.OpenInference/Conventions/openinference-conventions.json";
const string ConstantsRelativePath = "src/WithLove.OpenInference/OpenInferenceAttributes.g.cs";

var verifyOnly = args is ["verify"];
if (!verifyOnly && args is not [] and not ["generate"])
{
    throw new InvalidOperationException(
        "Usage: dotnet run --project tools/WithLove.OpenInference.Generator -- [generate | verify]");
}

var repositoryRoot = FindRepositoryRoot(Directory.GetCurrentDirectory());
var manifestPath = Path.Combine(repositoryRoot, ManifestRelativePath);
var constantsPath = Path.Combine(repositoryRoot, ConstantsRelativePath);

using var manifest = JsonDocument.Parse(await File.ReadAllTextAsync(manifestPath));
var manifestAttributes = manifest.RootElement
    .GetProperty("attributes")
    .EnumerateArray()
    .Select(attribute => attribute.GetProperty("name").GetString()
        ?? throw new InvalidOperationException("A conventions attribute is missing its name."))
    .ToHashSet(StringComparer.Ordinal);
string[] attributes =
[
    "document.content",
    "document.id",
    "document.metadata",
    "document.score",
    "exception.escaped",
    "input.mime_type",
    "input.value",
    "openinference.project.name",
    "openinference.span.kind",
    "output.mime_type",
    "output.value",
    "retrieval.documents",
    "session.id",
    "tag.tags",
    "tool.description",
    "tool.id",
    "tool.name",
    "user.id"
];
var missingAttributes = attributes.Where(attribute => !manifestAttributes.Contains(attribute)).ToArray();
if (missingAttributes.Length > 0)
{
    throw new InvalidOperationException(
        $"The conventions manifest is missing required WithLove attributes: {string.Join(", ", missingAttributes)}.");
}

var generatedConstants = GenerateConstants(attributes);

if (verifyOnly)
{
    if (!ArtifactByteComparison.MatchesCanonicalUtf8(constantsPath, generatedConstants))
    {
        throw new InvalidOperationException(
            $"Generated artifact '{constantsPath}' is stale. Run the generator with 'generate'.");
    }

    Console.WriteLine("Generated OpenInference attributes are current.");
}
else
{
    await File.WriteAllBytesAsync(constantsPath, CanonicalText.GetUtf8Bytes(generatedConstants));
}

static string GenerateConstants(IReadOnlyList<string> attributes)
{
    var identifiers = attributes
        .Select(attribute => (Attribute: attribute, Identifier: ToIdentifier(attribute)))
        .ToArray();
    var duplicate = identifiers
        .GroupBy(item => item.Identifier, StringComparer.Ordinal)
        .FirstOrDefault(group => group.Count() > 1);
    if (duplicate is not null)
    {
        throw new InvalidOperationException(
            $"Multiple OpenInference attributes map to generated identifier '{duplicate.Key}'.");
    }

    var output = new StringBuilder();
    output.AppendCanonicalLine("// <auto-generated />");
    output.AppendCanonicalLine();
    output.AppendCanonicalLine("namespace WithLove.OpenInference;");
    output.AppendCanonicalLine();
    output.AppendCanonicalLine("/// <summary>OpenInference reserved attribute names from the pinned conventions manifest.</summary>");
    output.AppendCanonicalLine("public static class OpenInferenceAttributes");
    output.AppendCanonicalLine("{");
    foreach (var item in identifiers)
    {
        output.Append("    public const string ")
            .Append(item.Identifier)
            .Append(" = \"")
            .Append(item.Attribute)
            .AppendCanonicalLine("\";");
    }

    output.AppendCanonicalLine("}");
    return output.ToString();
}

static string ToIdentifier(string name)
{
    var output = new StringBuilder();
    foreach (var segment in name.Split(['.', '_', '-'], StringSplitOptions.RemoveEmptyEntries))
    {
        if (segment.Equals("openinference", StringComparison.OrdinalIgnoreCase))
        {
            output.Append("OpenInference");
            continue;
        }

        output.Append(char.ToUpperInvariant(segment[0]));
        output.Append(segment.AsSpan(1));
    }

    return output.ToString();
}

static string FindRepositoryRoot(string startDirectory)
{
    for (var directory = new DirectoryInfo(startDirectory); directory is not null; directory = directory.Parent)
    {
        if (File.Exists(Path.Combine(directory.FullName, "WithLoveShop.slnx")))
        {
            return directory.FullName;
        }
    }

    throw new InvalidOperationException("Could not locate the repository root.");
}
